baseURL: https://cjting.me
title: CJ's Blog
metaDataFormat: yaml
hasCJKLanguage: true
languageCode: zh-cn
SectionPagesMenu: main

author:
  name: CJ

permalinks:
  go: /:year/:month/:day/:filename/
  linux: /:year/:month/:day/:filename/
  misc: /:year/:month/:day/:filename/
  web2.0: /:year/:month/:day/:filename/

params:
  author: CJ
  default_cover: http://asset.cjting.cn/FuPonm3F5RFQTgT1UCWAtZArt1Om.jpeg
  baidu_token: 4f34ee3c85734c8235badd2b99b092a6
