baseURL: http://cjting.me
title: CJ Ting's Blog
metaDataFormat: yaml
disableKinds: ["RSS", "sitemap"]
hasCJKLanguage: true
SectionPagesMenu: main
params:
  author: CJ Ting
  default_cover: http://ww2.sinaimg.cn/large/9b85365dgw1f7brwadugzj21kw11x1kx.jpg
  baidu_token: 4f34ee3c85734c8235badd2b99b092a6
