# baseURL: https://cjting.me
baseURL: http://tmp2.haibao6688.com
title: CJ's Blog
metaDataFormat: yaml
hasCJKLanguage: true
languageCode: zh-cn
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
SectionPagesMenu: main
rssLimit: 10

author:
  name: CJ Ting

permalinks:
  go: /:year/:month/:day/:filename/
  linux: /:year/:month/:day/:filename/
  mac: /:year/:month/:day/:filename/
  misc: /:year/:month/:day/:filename/
  web2.0: /:year/:month/:day/:filename/

params:
  author: CJ
  default_cover: http://ww2.sinaimg.cn/large/9b85365dgw1f7brwadugzj21kw11x1kx.jpg
  baidu_token: 4f34ee3c85734c8235badd2b99b092a6
